dev_portailconcept:
    image: tutum/apache-php
    ports:
        - "80:80"
    volumes:
        - /opt/local/web/portailconcept:/app
        - /opt/local/web/btp/docker/php.ini:/etc/php5/apache2/conf.d/30-custom.ini
    environment:
        - ALLOW_OVERRIDE=true
    links:
        - dev_db_portailconcept:dev_db_portailconcept

dev_db_portailconcept:
    image: mysql
    volumes:
        - /tmp/mysql:/var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=root